name: documentation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          apt-get install pandoc
          pip install sphinx nbsphinx furo
          pip install nbconvert nbformat
          pip install pandoc
          pip install sphinx-design
      - name: Sphinx build
        run: |
          # sphinx-build source build
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true